#!/bin/bash

# Script to fix missing framework dependencies in Simple Calendar Xcode project
# Run this from the project root directory

echo "To fix the missing EventKit framework dependency:"
echo ""
echo "1. Open Simple Calendar.xcodeproj in Xcode"
echo "2. Select the 'Simple Calendar' target in the Project Navigator"
echo "3. Go to the 'General' tab"
echo "4. Scroll down to 'Frameworks, Libraries, and Embedded Content'"
echo "5. Click the '+' button"
echo "6. Add the following frameworks one by one:"
echo ""
echo "   Required Frameworks:"
echo "   - EventKit.framework (NOT needed for tvOS - conditionally excluded in code)"
echo "   - MapKit.framework (NOT needed for tvOS - conditionally excluded in code)"
echo "   - CoreLocation.framework"
echo "   - AuthenticationServices.framework (NOT needed for tvOS - Google OAuth excluded)"
echo "   - WeatherKit.framework"
echo "   - SwiftData.framework (if not already present)"
echo ""
echo "   Make sure each framework is set to 'Do Not Embed'"
echo ""
echo "7. Build the project again"
echo ""
echo "Alternatively, if you want to do this via command line (advanced):"
echo "You would need to manually edit the project.pbxproj file to add the frameworks,"
echo "but this is error-prone and not recommended."
echo ""
echo "The frameworks are needed for:"
echo "- EventKit: Calendar event access and management (excluded on tvOS)"
echo "- MapKit: Location maps in event details (excluded on tvOS)"
echo "- CoreLocation: Location services"
echo "- AuthenticationServices: Google OAuth (excluded on tvOS)"
echo "- WeatherKit: Weather data"
echo "- SwiftData: Data persistence"
echo ""
echo "Note: On tvOS, the app works with local events, holidays, and templates only."
echo "EventKit, Google Calendar integration, and web authentication are disabled on tvOS."

